#!/bin/sh

java -jar "C:/soft/!UTILS/ClosureCompiler/compiler.jar" --charset=utf8 --js=src/udeferred.js --js=src/crc32.js --js=src/apng-canvas.js --js_output_file=apng-canvas.min.js

git add apng-canvas.min.js
